import type { Metadata } from "next";
import "./globals.css";
import {Poppins} from "next/font/google"

const poppins_init = Poppins({
  subsets: [],
  variable: "--font-poppins",
  weight: ["300"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins_init.variable }>{children}</body>
    </html>
  );
}
